server:
    port: 8088
spring:
    datasource:
        url: jdbc:mysql://xxx:3306/test_db_name?characterEncoding=utf-8&serverTimezone=GMT%2B8
        username: root
        password: xx
jwt:
    token:
        secretKey:
        refreshTime: 2592000
        expiresTime: 2592000
logging:
    level:
        sql: debug
        com.eric.app.mapper: debug

mybatis-plus:
    configuration:
        log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl
    global-config:
        enable-sql-runner: true





